### ISSUE TITLE
Simplify list of locales

### ISSUE THREAD

**Issue by kaldoran** [Gwillald/Architect#2]
Hi again,

Here is another issue but this time about the select_locales function

I've come out with this solution ( excluding the wc -l )
```
> cat /etc/locale.gen | sed -n "s/#\([^\.]*\)\.UTF-8.*/\1/p" | wc -l
148
> cat /etc/locale.gen | sed -n "s/#\([^\.]*\)\.UTF-8.*/\1/p" | uniq | wc -l
148
```

I also want to point out that on my system the uniq is useless :)

**Comment by Gwillald** [comment]
There are two problems with your suggestion:

First, it outputs one of the examples in comments on the first line.

```
  en_US
aa_DJ
af_ZA
an_ES
ar_AE
...
```

Then, it does not print the uncommented locale.

**Comment by kaldoran** [comment]
```
cat /etc/locale.gen | sed -n "s/#\([^ \.]*\)\.UTF-8.*/\1/p"
```
In order to fix the first problem [Just add space in the first pattern.

If you also want to add the uncommented locale : 
```
 cat /etc/locale.gen | sed -n "s/#\?\([^ \.]*\)\.UTF-8.*/\1/p"
```

Just add the "\?" after the '#'
